web:
  uploads-path: /Users/uup/IdeaProjects/lseaes/uploads
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.74.106.133:3306/lseaes?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: Cc5971415.
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: file:${web.uploads-path}